### PR TITLE
release: 0.3.5

### PR DESCRIPTION
**Pull request by wildintellect**
## Summary:
- **What** did I do? bumped release to 0.3.5
- **Why** *** did I do it? (What was the motivation?) #120
- **How** *** can someone test or demo my changes? Install package, run a notebook outside of the code clone folder.

  _*** **When relevant, use screenshots to document**_

## Checklist before requesting a review:
- [x] My code follows the guidelines of this project
- [x] I  performed a self-review of my code changes
- [x] I have added my changes to the change log (`HISTORY.rst`)
- [x] I have completed spell-checking, removed unnecessary print statements & commented-out code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by anilnatha — APPROVED** [review]
LGTM!

**Review by emmalu — APPROVED** [review]

**Comment by Maranhao6456** [comment]
Hi,

I'm trying to reproduce the code in my google colab but I'm not having success. In addition to the demo code, is there any other more didactic guide on how to install the dependencies and the OS environment?
Note: I don't have developer skills.

**Comment by emmalu** [comment]
Hi @Maranhao6456 - thanks for your interest in this library. Regarding your inquiry:

> In addition to the demo code, is there any other more didactic guide on how to install the dependencies and the OS environment?

While you **_should_** be able to install the repo directly from its GitHub URL, followed by manually setting of environment variables that point to the STAC catalog URLs of interest (as shown in the [constants](https://github.com/MAAP-Project/stac_ipyleaflet/blob/main/stac_ipyleaflet/constants.py) file)...

It appears that Google Collab blocks certain Jupyter Widgets so you will likely not be able to load the interactive map output.
image
While we can't prioritize this issue given that the library works within the intended (pre-configured) Development Environments of interest, we can try to keep this in mind in future development phases.

**Comment by Maranhao6456** [comment]
Hi @emmalu,

Thank you for the answer. What would be these intended (pre-configured) Development Environments of interest?

**Comment by emmalu** [comment]
They are custom cloud infrastructures for research teams at NASA.

**Comment by wildintellect** [comment]
Please move this side discussion to the https://github.com/MAAP-Project/stac_ipyleaflet/discussions

**Pull request merged**
