### PR TITLE
initial config without riotiler

### PR DESCRIPTION
**Pull request by emmalu**
rio-tiler and rioxarray packages both give the following:

`ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.`

### CODE REVIEW

**Comment by emmalu** [comment]
@wildintellect one thing that comes to mind is: should we 'mix' the use of both pip and conda to handle the different package installs? or perhaps move everything to be handled by conda?

**Comment by wildintellect** [comment]
Generally move as much as possible to conda, I think it the right answer. Only resort to pip when conda doesn't have the right versions. But I'll look at this more closely.

**Comment by wildintellect** [comment]
The bigger issue is that the `pip` is being run outside the conda environment. I dug deeper...
- https://github.com/devcontainers/images/blob/794860b0aad041def006226c0849c1096a1edf8d/src/miniconda/.devcontainer/Dockerfile#L46-L48 does not read the environment.yml (this is what builds the microsoft image `mcr.microsoft.com/devcontainers/miniconda:0-3) so that all happens before the image is pulled. "For convenience, this definition will automatically install dependencies from the environment.yml" appears to be untrue, [source](https://github.com/devcontainers/templates/tree/main/src/miniconda), I don't think they use the right Docker command. I think it's supposed to be ONBUILD RUN not RUN on https://github.com/devcontainers/images/blob/794860b0aad041def006226c0849c1096a1edf8d/src/miniconda/.devcontainer/Dockerfile#L47 :lady_beetle:  Pangeo has a good example https://github.com/pangeo-data/pangeo-docker-images/blob/master/base-image/Dockerfile
- Enabling those lines in the Dockerfile fails, because it's executing as the wrong user `vscode` instead of root. I'm actually thinking this whole image is useless, even though it gives the `conda` group ownership over the conda install, the permissions are not correct all files and attempting to install anything with conda fails as the the `vscode` user. We probably should report a :lady_beetle: 
- pip install once the container is up and at a conda terminal does work, no issues. I could load the widget in the VSCode notebook viewer but it doesn't work right with ipywidgets. So we do need jupyterlab, @abarciauskas-bgse the readme doesn't have any instructions on if anything is needed to register ipyleafet inside jupyterlab.

## Options
- Start with a different base image (we could reuse some of the method [MS uses](https://github.com/devcontainers/images/blob/main/src/miniconda/.devcontainer/Dockerfile#L46-L48)) or go the micromamba route (side note: this version of miniconda does not seem to have the libmamba solver - no idea why)
- Try changing to root to add to the conda install, or change the permissions to make it all owned by `vscode` user.

**Comment by wildintellect** [comment]
@emmalu I think I have a fix, see #49

**Review by wildintellect — APPROVED** [review]
If this is working now for @emmalu and @edkeeble then please proceed.

**Pull request merged**
