### PR TITLE
Refactor: restructure core widget

### PR DESCRIPTION
**Pull request by jjfrench**
Wasn't entirely complete with what I wanted to pull out from core.py but the idea was separate the widgets from each other instead of it feeling like we were adding stac_discovery onto the biomass_layers

### CODE REVIEW

**Comment by emileten** [comment]
@jjfrench am I right that this is refactoring (renaming `core` to `base_layer`, putting the histogram stuff from`base_layer` to `biomass_layers.histograms` and the biomass stuff from `base_layer` to `biomass_layers.biomass_widget`) but not changing any behavior or fixing bugs ? If so looks good to me. Otherwise, I haven't digged much into this code in the past so can't review the details, but, I guess you tested locally that things are still working as expected after these changes (looks like we don't have any test) ?

**Comment by jjfrench** [comment]
@emileten Right, `core` -> `base_widget` and pulled out histogram/biomass_layers from `core` into the biomass_layers widget. I tried to keep the functionality the same so I added `histogram_on_click` to pass the button event through and of course, some references to `self` became the class. Aside from that, nothing else added.

**Comment by jjfrench** [comment]
@emileten Right, `core` -> `base_widget` and pulled out histogram/biomass_layers from `core` into the biomass_layers widget. I tried to keep the functionality the same so I added `histogram_on_click` to pass the button event through and of course, some references to `self` became the class. Aside from that, nothing else was added.

**Review by emileten — APPROVED** [review]
LGTM although I am not super familiar with the code base.

**Comment by jjfrench** [comment]
@abarciauskas-bgse , do you have thoughts on this PR?

**Pull request closed without merging**
