### PR TITLE
Ab/fix other titiler endpoints

### PR DESCRIPTION
**Pull request by abarciauskas-bgse**
As noted in #50 we deployed a new instance of titiler and some functionality changed - we lost /stac endpoints /point endpoints (doesn't matter for this repo at the moment) and /mosaic endpoints changes (by dropping the additional /mosaicjson path)

Here I've updated the layer instantiation to address those changes by using the old titiler instance for those routes which we lost with the new titiler instance. The old titiler instance is now behind the domain name https://titiler-stac.maap-project.org

### CODE REVIEW

**Comment by jjfrench** [comment]
Changes look good, though I still can't seem to get the Icesat2 layers to show up

**Comment by abarciauskas-bgse** [comment]
@jjfrench it's really slow for me unless I zoom in (to the boreal region) at about zoom level 8, did you try to zoom in a lot to the boreal region (like Canada) ?

**Comment by jjfrench** [comment]
@abarciauskas-bgse , I hadn't - that helps
If data loads better at a specific zoom, it would be nice to add that into the layer selection

**Review by jjfrench — APPROVED** [review]
Changes look good from the position that some of the titiler functionality may be added back in and this repo can be updated again

**Pull request merged**
